Feature/book creation
Raj-kadevar/user-management pull request #7
Opened 2023-08-07 08:33 UTC by Raj-kadevar

2023-08-07 08:36 UTC, Dhruvi-Makwana commented on book/forms.py
> +    #     return  creator
remove commented code

2023-08-07 13:36 UTC, HARSHKALAL commented on book/urls.py
>      path('logout/',views.on_logout,name="logout"),
avoid write views everytime.

.views import <API name>.

2023-08-07 13:41 UTC, HARSHKALAL requested changes

2023-08-07 13:41 UTC, HARSHKALAL commented on book/urls.py
> +    path("update/<int:id>/",views.update,name="update"),
what update ? writer propoer name

2023-08-08 08:47 UTC, Dhruvi-Makwana commented on book/templates/book/index.html
form next time try to write delete-book or delete_book

2023-08-08 08:51 UTC, Dhruvi-Makwana commented on book/views.py
>              errors = book.errors
if you use LoginRequiredMixin then you don't have to write if condition

2023-08-08 08:52 UTC, Dhruvi-Makwana commented on book/forms.py
>  class UpdateFrom(forms.ModelForm):
whose updateForm ? write BookUpdateForm instend

2023-08-09 06:13 UTC, yatishTT approved these changes

2023-08-09 06:13 UTC, merged